name: build

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install make dependencies
        run: sudo apt install qt5-default qttools5-dev cmake extra-cmake-modules make
      - name: Download Qpdf Tools Code
        uses: actions/checkout@v3
      - name: Configure
        run: cmake .
      - name: Compile
        run: make
      - name: Install
        run: sudo make install
