name: build

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: download Qpdf Tools Code
      uses: actions/checkout@v2
    - name: configure
      run: cmake .
    - name: make
      run: make
    - name: make install
      run: sudo make install
