name: build

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fix apt issue with Github Actions
        run: sudo apt update
      - name: Install make dependencies
        run: sudo apt install cmake extra-cmake-modules make qtbase5-dev qttools5-dev
      - name: Download Qpdf Tools Code
        uses: actions/checkout@v4
      - name: Configure
        run: cmake .
      - name: Compile
        run: make
      - name: Install
        run: sudo make install
