name: build

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
      - name: Download Qpdf Tools Code
        uses: actions/checkout@v3
      - name: Configure
        run: cmake .
      - name: Compile
        run: make
      - name: Install
        run: sudo make install
