name: Publish on Launchpad

on:
  push:
    tags:
      - "v*"

jobs:
  ppa:
    runs-on: ubuntu-latest
    steps:
      - name: Download Qpdf Tools Code
        uses: actions/checkout@v4
      - name: Fix apt issue with Github Actions
        run: sudo apt update
      - name: Install make dependencies
        run: sudo apt install cmake extra-cmake-modules make qtbase5-dev qttools5-dev wget devscripts debhelper
      - name: Get release source code
        run: wget https://github.com/silash35/qpdftools/archive/refs/tags/v3.0.0.tar.gz
      - name: Move release source code
        run: mv v3.0.0.tar.gz ./packages/dpkg/qpdftools_3.0.0.orig.tar.gz
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.PPA_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PPA_GPG_PASSPHRASE }}
      - name: Build package
        run: cd ./packages/dpkg/qpdftools/ && debuild -S
      - name: Publish PPA
        run: cd ./packages/dpkg/ && dput ppa:silash35/qpdftools qpdftools_3.0.0_source.changes
